# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79a6650bcacf6db1b6290a66defd78bcde5eb56b585f512eaae2ff1e05ed27835c23ca06dedd752047c8c43f19c041278fcc720544ea204034c198522151ba9b

test:
  secret_key_base: 3bb0eeebff8f4e55572cecaafc58c1233e6b293de45eeaaa1976cdc89638d54440a30fe4fb29b24d4689abb0698233881fe0c4e79f786c149d4a14f06b6b912d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
